apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubernetes-event-logger
  labels:
    app: kubernetes-event-logger
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-event-logger
    spec:
      restartPolicy: Always
      containers:
      - name: kubernetes-event-logger
        image: "gcosta/kubernetes-event-logger"
